### ISSUE TITLE
update README install symlink

### ISSUE THREAD

**Issue by morenopc** [bitpay/i-made-this#11]
Am I missing something? Or installation instructions at README needs to be updated? 

After run `~/projects$ ln -s ~/projects/mynode/node_modules ~/projects/i-made-this/stampingservice` I have:

```
~/projects$ ls -la i-made-this/stampingservice/
total 20
drwxrwxr-x 2 moreno moreno 4096 Mai  2 12:11 .
drwxrwxr-x 7 moreno moreno 4096 Mai  2 11:52 ..
-rw-rw-r-- 1 moreno moreno 6616 Mai  2 11:52 index.js
lrwxrwxrwx 1 moreno moreno   47 Mai  2 12:11 node_modules -> /home/moreno/projects/mynode/node_modules
-rw-rw-r-- 1 moreno moreno   50 Mai  2 11:52 package.json
```

but to fix:

```
~/projects/mynode$ bitcored
module.js:327
    throw err;
    ^

Error: Cannot find module 'stampingservice/package.json'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Function.setupServices (/home/moreno/projects/mynode/node_modules/bitcore-node/lib/scaffold/start.js:51:30)
    at start (/home/moreno/projects/mynode/node_modules/bitcore-node/lib/scaffold/start.js:203:31)
    at Object.main [as daemon] (/home/moreno/projects/mynode/node_modules/bitcore-node/lib/cli/daemon.js:38:3)
    at Liftoff.<anonymous> (/home/moreno/.nvm/versions/node/v4.4.3/lib/node_modules/bitcore/node_modules/bitcore-node/lib/cli/bitcored.js:29:16)
    at Liftoff.<anonymous> (/home/moreno/.nvm/versions/node/v4.4.3/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/liftoff/index.js:197:12)
    at Liftoff.<anonymous> (/home/moreno/.nvm/versions/node/v4.4.3/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/liftoff/index.js:164:7)
```

I also had to create:

```
~/projects$ ln -s ~/projects/i-made-this/stampingservice ~/projects/mynode/node_modules
~/projects$ ls -la mynode/node_modules/
total 24
drwxrwxr-x  6 moreno moreno 4096 Mai  2 12:13 .
drwxrwxr-x  4 moreno moreno 4096 Mai  2 12:05 ..
drwxrwxr-x  4 moreno moreno 4096 Mai  2 11:59 async
drwxrwxr-x  2 moreno moreno 4096 Mai  2 11:59 .bin
drwxrwxr-x  7 moreno moreno 4096 Mai  1 17:12 bitcore-lib
drwxrwxr-x 13 moreno moreno 4096 Mai  1 17:15 bitcore-node
lrwxrwxrwx  1 moreno moreno   55 Mai  2 12:13 stampingservice -> /home/moreno/projects/i-made-this/stampingservice
```

**Comment by bachvtuan** [comment]
I 'm facing your issue too. To fixed this, I copied "stampingservice" folder into node_modules from bitcored modules. 
My path is /home/geek/Tools/node-v4.4.3-linux-x64/lib/node_modules/bitcore/node_modules
Hopefully, the author will update document .

**Comment by bitjson** [comment]
Hi all, please see the latest master for a Bitcore v4 compatible version. I think these issues have been fixed as of: https://github.com/bitpay/i-made-this/pull/12. Thanks!

**Comment by streamerd** [comment]
Hi people, I am bringing up the issue again but could not achieve running "bitcored" command.

@bitjson hi, I am currently using the v4 compatible version, facing the exact same issue of @morenopc  's. Then I've tried @bachvtuan 's solution, it has given me the following:

```
Users/foo/.nvm/versions/node/v4.8.7/lib/node_modules/bitcore/node_modules/stampingservice/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: Module version mismatch. Expected 46, got 48.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/Users/pseudo/.nvm/versions/node/v4.8.7/lib/node_modules/bitcore/node_modules/stampingservice/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/Users/foo/.nvm/versions/node/v4.8.7/lib/node_modules/bitcore/node_modules/stampingservice/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

```
$nvm use v4
$Now using node v4.8.7 (npm v2.15.11)
