### ISSUE TITLE
Error: Cannot find module 'app'

### ISSUE THREAD

**Issue by bethnull** [bitpay/i-made-this#16]
Hi,

After following the instructions of the repo regarding the installation of the Electron App:

```
npm install electron-prebuilt -g

cd i-made-this
npm install
bower install
electron .
```

When I execute `electron .` a window appears with an error saying:

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: Cannot find module 'app'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (/xxx/xxx/.nvm/versions/node/v4.4.5/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/xxx/xxx/i-made-this/main.js:2:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

Any idea about this error?

Kind regards, beth.

**Comment by bethnull** [comment]
It's related with new electron version.

Fixed in a pull request.
